--DDL(데이터 정의어)
--테이블 생성하기
CREATE TABLE BOARD(
    --컬럼 추가
    BNO NUMBER(10),
    TITLE VARCHAR2(200) NOT NULL,
    CONTENT VARCHAR2(2000), 
    WRITER VARCHAR(50) NOT NULL,
    REG_DATE DATE NOT NULL
);

--PRIMARY KEY(기본키) 설정
ALTER TABLE BOARD
ADD CONSTRAINT pk_board_bno
PRIMARY KEY (BNO);


SELECT * FROM BOARD;

--댓글 테이블 생성
CREATE TABLE REPLY(
    RNO NUMBER(10),
    R_CONTENT VARCHAR2(1000),
    R_WRITER VARCHAR2(50) NOT NULL,
    BNO NUMBER(10)
);

--PK 설정
ALTER TABLE REPLY
ADD CONSTRAINT pk_reply_rno
PRIMARY KEY (RNO);

--FK 설정
ALTER TABLE REPLY
ADD CONSTRAINT fk_reply_bno
FOREIGN KEY (BNO)
REFERENCES BOARD (BNO);

--컬럼 변경
ALTER TABLE BOARD 
ADD(VIEW_COUNT NUMBER(10));

ALTER TABLE BOARD 
DROP COLUMN REG_DATE;

DROP TABLE REPLY;
DROP TABLE BOARD;


